### ISSUE TITLE
ts-support branch aliases are not working.

### ISSUE THREAD

**Issue by stdout-reach** [ReactTraining/react-workshop#19]
macOS Catalina 10.15.4
NodeJS 10.15.3
NPM: 6.4.1
Yarn: 1.22.4

Steps taken:
cloned repo, fetched the `ts-support` branch to follow along videos using typescript. However running the command

```
yarn start lecture
```
followed by any prompt always opens up the entire complete application and never the corresponding lecture or exercise.

Swapping to `master` branch, the alias issue does not exist.

Steps I've tried to alleviate. 
Stepped through with the debugger, I've found that the app starts up in YesterTech/entry.js with all aliases setup.
Removed node_modules and reinstalled with npm
Removed node_modules and reinstalled with yarn
Removed the package-locks/yarn.lock files and reinstalled.

**Comment by bradwestfall** [comment]
Hi @stdout-reach that branch was made as somewhat of an impromptu branch for a one-off client. The repo doesn't really support TS yet in a way that we're maintaining regularly. If he has time, I think @chancestrickland was the one who did that branch so maybe he has a quick answer. I'll be doing new curriculum and revamps later this summer so I'll consider making TS fully supported at that point probably.

Also, what videos do you mean?

**Comment by stdout-reach** [comment]
@bradwestfall I see, I was able to get it somewhat working for now. Just a few tweaks on master branch.
