### ISSUE TITLE
Exercises will not run

### ISSUE THREAD

**Issue by bumbleb2nawork** [ReactTraining/react-workshop#32]
# Bug

`npm start` will only compile the full app (ie: either YesterTech or ProjectPlanner) to localhost:3000

## Environment:

Windows 10 with latest updates. Either latest Chrome or latest Edge browser. Latest node.js LTS with latest npm.

## Steps to reproduce:

1. enter command `npm start`
2. make a choice leading to compile.

_or:_ enter `npm start core-v1 1` and enter `1` for 'exercise'
_or:_ enter `npm start core-v2 1` and enter `1` for 'exercise'

**Comment by bradwestfall** [comment]
Are you using WSL for windows?

**Comment by bumbleb2nawork** [comment]
No sir

**Comment by bradwestfall** [comment]
That's a big part of the Readme (https://github.com/ReactTraining/react-workshop#windows-users)

Also do you mind if I ask, are you taking or about to take one of our workshops? It doesn't matter if you're not, just wanted to make sure you're good to go if you are

**Comment by bumbleb2nawork** [comment]
Ok I thought that was just for using `nvm` to switch versions of nodejs. It didn't sound like a requirement to run on Windows.

Took training a couple of months ago and was interested in trying out the typescript version.

**Comment by bradwestfall** [comment]
oh cool, yea have fun! We have to jump through extra hooks to get the curriculum menu system working on all platforms, so we just decided to always recommend WSL since it's the most stable for us

**Comment by bumbleb2nawork** [comment]
I am using Powershell and am not getting any weird menu errors like it says in that seciton. Powershell output reads, "Go to localhost:3000" and finishes compiling. 

Maybe WSL will somehow help.
