### ISSUE TITLE
Windows compile

### ISSUE THREAD

**Issue by BumbleB2na** [ReactTraining/react-workshop#33]
# Bug
On Windows `npm start` from cmd or powershell will only compile the full app (ie: either YesterTech or ProjectPlanner) to localhost:3000.

## Expected result:
It compiles the chosen exercise to localhost:3000

## Environment:
Windows 10 with latest updates. Either latest Chrome or latest Edge browser. Latest node.js LTS with latest npm.

_Note: I do not have WSL[2] installed as suggested in the Readme.md_

## Steps to reproduce:
1. open powershell on windows in project directory
1. enter command `npm start`
1. make choices in terminal that lead to webpack compile of an exercise
1. navigate to localhost:3000 in web browser

or: enter `npm start core-v1 1` and enter 1 for 'exercise'
or: enter `npm start core-v2 1` and enter 1 for 'exercise'

**Comment by BumbleB2na** [comment]
I believe I found a fix that doesn't require WSL. If you give me permission to create a branch and a PR I'll help fix it.

**Comment by bradwestfall** [comment]
It's best to make a Fork to do a PR. But yea that would be great, thank you
