### ISSUE TITLE
Fails to `npm i` with Node 16

### ISSUE THREAD

**Issue by soffes** [ReactTraining/react-workshop#38]
First off, I'm not familiar with JavaScript so maybe this obvious but it took me a long time to figure this out. Thought I'd open an issue in case someone else sees this. Might be good to add a note to the README.

I had node installed from Homebrew. This currently installs Node 16. One of the dependencies of this project, `node-sass`, [isn't compatible with Node 16](https://github.com/sass/node-sass/issues/3106).

After awhile, I figured out how to workaround this:

1. Uninstall Homebrew's Node: `brew uninstall node`
2. Install NVM. I did `brew install nvm` and then followed the instructions to add it to my shell.
3. Install Node 15: `nvm install v15 && nvm use v15`
4. After restarting your shell, you can run `node -v` to confirm you have Node 15 and then run `npm i` like normal.

**Comment by bradwestfall** [comment]
Thank you, I'll take a look at Node 16 later today to see if there's any problems. I currently use Node 14
