### ISSUE TITLE
Options for Lesson 4, lectures 1 & 2 load the wrong page on localhost

### ISSUE THREAD

**Issue by GemKosan** [ReactTraining/react-workshop#45]
I get the default class page (screenshot below) when I try to load lesson 4 lecture 1 and lesson 4 lecture 2. Shouldn't this load something else?

**These options:**
```
[2] lecture-1-data-fetching
[3] lecture-2-layout-effects
```
**Example output**
```
Running Lesson: 04-side-effects/lecture-2-layout-effects
Go to: http://localhost:3000
```

**Screenshot of localhost:3000**
<img width="1380" alt="Screen Shot 2022-04-03 at 3 17 37 PM" src="https://user-images.githubusercontent.com/51011468/161446859-e120147d-e62a-4a09-8a46-5c84fc9c3039.png">

**Comment by GemKosan** [comment]
Oops, I see the lesson uses the courses page. I just had to click the nav link :) 
NVM...

**Comment by bradwestfall** [comment]
:) no worries. Thanks @GemKosan
