### ISSUE TITLE
Search Input field is missing id={searchId}

### ISSUE THREAD

**Issue by OlgaD** [ReactTraining/react-workshop#56]
Search Input field is missing id={searchId} in react\_full-app\SearchVacationsForm.tsx
https://github.com/ReactTraining/react-workshop/blob/a867be310892d67e21b0808b0bbc9e13df7c562b/react/_full-app/SearchVacationsForm.tsx#L67

**Comment by bradwestfall** [comment]
Thank you, It's fixed
